# \u2705 Server Port
server.port=8080

# \u2705 H2 DATABASE (ACTIVE)
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# \u2705 JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# \u2705 H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# \u2705 MYSQL (USE LATER)

# spring.datasource.url=jdbc:mysql://localhost:3306/bank_db
# spring.datasource.username=root
# spring.datasource.password=your_password
